name: moniepoint
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fade_out_particle: ^1.2.1
  flutter_screenutil: ^5.9.0
  intl: ^0.18.1
  flutter_animate: ^4.2.0+1
  flutter_hooks: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/icon/

  fonts:
    - family: Inter
      fonts:
        - asset: asset/font/Inter-Regular.otf
